- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/templates/nidhogg.yaml
For now this is needed, so we can override the load balancer ip range
and ingress lb ip when installing nidhogg from mukube-configurator.
**Description of your changes:** ^
Checklist:
> Support overriding yggdrasil values

- charts/argo-cd/chart/Chart.yaml
- charts/nidhogg/chart/Chart.yaml
This is a hotfix for the issue with nidhogg not release and therefore argocd not releasing. The changes to charts that are dependent on each other has to come consecutively. 
Checklist:
> Reverted change to nidhogg back and bumped argocd version

- charts/argo-cd/chart/Chart.yaml
- charts/nidhogg/chart/Chart.yaml
Nidhogg has to be reverted back to old dependency since workflow still finds changed chart
Checklist:
> Nidhogg has to be reverted back to old dependency

- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
Changed so cni dependency now points to our own helm repo
Checklist:
> Changed cni dependency to point to new helm chart repo

- charts/lb-proxy/chart/.helmignore
- charts/lb-proxy/chart/Chart.yaml
- charts/lb-proxy/chart/templates/_helpers.tpl
- charts/lb-proxy/chart/templates/configmap.yaml
- charts/lb-proxy/chart/templates/deployment.yaml
- charts/lb-proxy/chart/templates/service.yaml
- charts/lb-proxy/chart/values.yaml
This is the service CRI-O and Argo will point to and use as http proxy.
The service is responsible for routing the traffic to a real http proxy
server, either running in the cluster and/or a external proxy server. If
both a internal and external proxy server are provided, the external
server is used a backup in case the internal is down.
**Description of your changes:** ^
Checklist:
> Add lb-proxy service

- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/values.yaml
The lb-proxy service needs to start early so CRI-O and Argo can point to
it as use it as http proxy.
Checklist:
> nidhogg: Add lb-proxy as dependency

- charts/argo-cd/chart/Chart.yaml
- charts/argo-cd/chart/templates/_helpers.tpl
- charts/argo-cd/chart/templates/configmap.yaml
- charts/argo-cd/chart/values.yaml
This is needed so Argo can run in a air gapped environment where all
traffic must go through a proxy server.
We use a configmap as templating isn't supported in the values file.
**Description of your changes:** ^
Checklist:
> argo-cd: Support specifying a HTTP proxy server

- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/templates/nidhogg.yaml
The internal TCP load balancer (lb-proxy subchart), Argo proxy config
(argo-cd-proxy-chart subchart) and custom root certificate
(argo-cd-proxy-chart subchart) are configured by
mukube-configurator[1][2] by setting values.
This means the values must stay in place, so pass them to the nidhogg
Argo application.
[1] https://github.com/distributed-technologies/mukube-configurator/pull/36
[2] https://github.com/distributed-technologies/mukube-configurator/pull/37
**Description of your changes:** ^
Checklist:
> nidhogg: Ensure proxy and root certificate values aren't "reverted"

- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/values.yaml
They aren't needed as we packaging the dependencies and Argo fails
deploying if they can't be reached (ex: in a air-gapped environment).
Checklist:
> nidhogg: Remove chart repositories from Argo

- README.md
I have removed an old part of the documentation that said you needed to add a new service to the matrix in the workflows. These are not dynamically found. 
Checklist:
> Removed old documentation referencing matrices

- .github/workflows/dependency-checker.yaml
Prefix the branch names with `update/`. With this change the update branches will be easily identifiable and grouped at the end when listing branches.
Checklist:
> workflow: Rename branches for automatic dep updates

- charts/kafka/chart/Chart.yaml
Update the strimzi operator to mitigate exploit
see https://github.com/strimzi/strimzi-kafka-operator/discussions/6023 for details.
Checklist:
> Hot fix/strimzi log4j mitigation

- charts/ntp/chart/Chart.yaml
- charts/ntp/chart/templates/daemonset.yaml
- charts/ntp/chart/templates/deployment.yaml
- charts/ntp/chart/values.yaml
- charts/ntp/container/chrony-client.conf
- charts/ntp/container/chrony-server.conf
- charts/ntp/container/docker-entrypoint.sh
This is useful if the cluster is running in a air-gapped environment and
a internal NTP server is available.
Checklist:
> ntp: Support overriding the NTP server

- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
0335867 ("cni: Switch CNI to Cilium from Weave Net")[1]
[1] https://github.com/distributed-technologies/helm-charts/pull/224
Checklist:
* It has been tested without Argo, but traffic is flowing.
> nidhogg: Bump CNI

- charts/ntp/chart/Chart.yaml
- charts/ntp/chart/values.yaml
The two capabilities set on the chronyd binary[1], must be allowed for
the binary to run. Due to a bug in CRI-O[2], CAP_NET_BIND_SERVICE was
unintentionally added by the runtime, which explain why the missing
capability wasn't caught in testing.
[1] CAP_SYS_TIME and CAP_NET_BIND_SERVICE
[2] https://github.com/cri-o/cri-o/pull/4923
Fixes: 3536bbf ("ntp: Fix the server can't listen on port 123 as
non-root")
Checklist:
> ntp: Add missing capability preventing chronyd from running

- charts/loki/chart/Chart.yaml
- charts/loki/chart/values.yaml
We do not need the loki stack w. promtail and other dependencies in this chart as we are moving to Grafana agents
Checklist:
> Change loki chart dependency to stand alone loki

- charts/ntp/chart/Chart.yaml
- charts/ntp/chart/values.yaml
There is no reason for maintaining the version in two places, just let
the chart use the chart version as tag for the image.
Fixes: 8044f04 ("ntp: Add missing capability preventing chronyd from
running")
Checklist:
> ntp: Fix wrong container image version

- charts/cortex/chart/Chart.yaml
- charts/cortex/chart/templates/bkt-claim.yaml
- charts/tempo-distributed/chart/Chart.yaml
- charts/tempo-distributed/chart/templates/bkt-claim.yaml
I have changed the key for the bucket name, to `generateBucketName` instead of `bucketName` since this is recommended by ceph.
https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#obc-custom-resource
Second point.
Checklist:
> cortex & tempo: Follow best practise for bucket name generation

- charts/exporters/README.md
- charts/exporters/chart/.helmignore
- charts/exporters/chart/Chart.yaml
- charts/exporters/chart/values.yaml
Added functionality to get kubernetes state metrics, node metrics and kafka metrics.
The charts are disabled by default and will have to be enabled in Yggdrasil. 
Checklist:
> Add exporters chart

- charts/rook/chart/Chart.yaml
- charts/rook/chart/values.yaml
It is unclear why this was added in[1], but we should use the image tag
specified in the upstream chart.
[1] https://github.com/distributed-technologies/services-rook/pull/4
Fixes: 98db9e9 ("argo, ceph, grafana, rook, traefik: bumped to newest versions")
Checklist:
> rook: Drop out-of-date image tag override

- charts/exporters/chart/Chart.yaml
- charts/exporters/chart/templates/cAdvisor-sm.yaml
- charts/exporters/chart/values.yaml
By adding the cAdvisor monitor back, we will be able to collect metrics on the container layer.
Checklist:
> Add cAdvisor monitor to exporters

- charts/exporters/chart/Chart.yaml
- charts/exporters/chart/templates/cAdvisor-sm.yaml
The namespace was changed to kube-system from {{ .Release.namespace }}
since the kubelet resides in the kube-system namespace
Checklist:
> exporters: Change namespace to kube-system

- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/templates/nidhogg.yaml
- charts/nidhogg/chart/values.yaml
A single switch is added, so they can easily be enabled in yggdrasil.
yggdrasil PR: https://github.com/distributed-technologies/helm-charts/pull/285
Checklist:
> nidhogg: Add switch for enabling the CNI's serviceMonitors

- charts/prometheus/chart/Chart.yaml
- charts/prometheus/chart/values.yaml
Some of the Grafana dashboards that we're using is build using [1]
these charts are build for the kube-prometheus-stack, for that reason
I have enabled the exporters in the kube-promehteus-stack again,
I have also removed the label requirement, since I see no reason to have them
The exporters helm chart has them disabled by default.
[1] https://github.com/kubernetes-monitoring/kubernetes-mixin
Checklist:
> Enable exporters in kube-prometheus-stack

- charts/grafana/chart/Chart.yaml
- charts/grafana/chart/dashboards/api-server.json
- charts/grafana/chart/dashboards/apiserver.json
- charts/grafana/chart/dashboards/cluster-total.json
- charts/grafana/chart/dashboards/etcd.json
- charts/grafana/chart/dashboards/k8s-resources-cluster.json
- charts/grafana/chart/dashboards/k8s-resources-namespace.json
- charts/grafana/chart/dashboards/k8s-resources-node.json
- charts/grafana/chart/dashboards/k8s-resources-pod.json
- charts/grafana/chart/dashboards/k8s-resources-workload.json
- charts/grafana/chart/dashboards/k8s-resources-workloads-namespace.json
- charts/grafana/chart/dashboards/kubectl.json
- charts/grafana/chart/dashboards/kubelet.json
- charts/grafana/chart/dashboards/namespace-by-pod.json
- charts/grafana/chart/dashboards/namespace-by-workload.json
- charts/grafana/chart/dashboards/node-cluster-rsrc-use.json
- charts/grafana/chart/dashboards/node-rsrc-use.json
- charts/grafana/chart/dashboards/nodes.json
- charts/grafana/chart/dashboards/persistentvolumesusage.json
- charts/grafana/chart/dashboards/pod-total.json
- charts/grafana/chart/dashboards/proxy.json
- charts/grafana/chart/dashboards/scheduler.json
- charts/grafana/chart/dashboards/workload-total.json
Currently we have some dashboards that are not working as intended,
seeing that we have updated the metrics exporters, but not the dashboards I suspect som deprecation within them.
Using the kubernets-mixin [1] repo (which is where I think the dashboards are comming from) I have generated a new set.
[1] https://github.com/kubernetes-monitoring/kubernetes-mixin#generate-config-files
I also removed helm escape characters in the json files
Checklist:
> grafana: Update dashboards

- charts/lightvessel/chart/Chart.yaml
- charts/lightvessel/chart/templates/_limitRange.yaml
Limit ranges are needed to set default resource requests and limits for
some namespaces. Preferably, resource limits are configured on each
pod, however, some helm charts deploy resources without limits and
without an option to specify limits.
This is the case for the rook-ceph-cluster chart.
Checklist:
> lightvessel: Allow LimitRange for namespaces

- charts/ceph/chart/Chart.yaml
- charts/ceph/chart/values.yaml
- charts/cortex/chart/Chart.yaml
- charts/cortex/chart/values.yaml
- charts/grafana/chart/Chart.yaml
- charts/grafana/chart/values.yaml
- charts/prometheus/chart/Chart.yaml
- charts/prometheus/chart/values.yaml
- charts/rook/chart/Chart.yaml
In yggdrasil 3.0.1 Resource Quotas were added to the namespaces for: rook-ceph, monitoring, and networking. That broke the current setup, since none of the resources deployed to those namespaces had any resource limits set. This PR fixes that.
We add resource limits to multiple helm charts.
Checklist:
> Add resource limits

- charts/squid/chart/Chart.yaml
Fixes: 723519c ("Add squid service")
Checklist:
> squid: Fix wrong chart name

- .github/configs/ct-install.yaml
- .github/configs/ct-lint.yaml
- .github/workflows/lint-and-test.yaml
- charts/tenant-base/README.md
- charts/tenant-base/chart/.helmignore
- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/_helpers.tpl
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/values.yaml
We want a basic helm chart that we can package with out tenant repo, that makes it easy for the tenants to set the values needed for their service to run.
Checklist:
> Add Tenant-base helm chart

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/values.yaml
This adds support for external secrets, which is the way we have decided
to handle secrets. The user must provide a name for the external secret
and the key (eg.: path in Vault). The keys in the secret are set as
environment variables in the container.
The user can set secretStore, but this is expected to be handled by a
Kustomization patch.
---
Checklist:
> tenant-base: Add support for external secrets

- .github/workflows/lint-and-test.yaml
- .github/workflows/publish.yaml
The GitHub Action broke[1] and the runner image already ships with helm,
so just use the preinstalled version.
[1] https://github.com/Azure/setup-helm/issues/97
[2] https://github.com/actions/runner-images/blob/1250493b2fdfdaf09244c1c87798ec1e65743212/images/linux/Ubuntu2004-Readme.md#package-management
> ci: Fix broken "Install Helm" step

- renovate.json
Our homebrewed dependency updater bumped the patch version, so configure Renovate to do the same.
Fixes: 5f4e9d5 ("Replace homebrewed dependency updater with Renovate")
Checklist:
> renovate: Bump chart version when updating dependencies

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/values.yaml
Add to the helm chart that tenants can create Kafka topics and do some limited configuration
Documentation will come in a later task as it depends on the format in another user-story. 
Checklist:
> Add to the halmchart that tenants can create kafka topics

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/values.yaml
I have referenced the acr-token imagePullSecret in the values file of the tenant-base helm chart. This is done because we from now on will deploy a secret containing our acr-token to each tenant namespace so that they can pull container images from our ACR. 
Checklist:
> tenant-base: Referenced acr-token in imagePullSecret

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/_helpers.tpl
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
Changed `deployments` from a list to a map, this is because merging lists often causes complete overrides if not done correctly, using maps merging is a lot simpler.
Checklist:
> Tenant-base: Change from list to map

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/configmap-kafka-topic.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/values.yaml
Through a ConfigMap a deployment can now configure if a deployment should be able to communicate with Kafka. A deployment can be configured to produce and consume to specific Kafka topics.
The ConfigMap will be digested by Kyverno which will generate the appropriate CiliumNetworkPolicy
Related PR:
https://dev.azure.com/energinet/Team%20DT/_git/flux-fleet-repo/pullrequest/28392
Checklist:
> tenant-base: Add Kafka communication to the tenant-base helm chart

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
Waiting on [helm-charts#399](https://github.com/distributed-technologies/helm-charts/pull/399)
These values has been hardcoded into the deployment, so that we can provide the users a standard way to interact with the liveness and readiness probes.
Checklist:
> Remove live/readi - ness probes from values.yaml

- charts/tenant-base/README.md
- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/_helpers.tpl
- charts/tenant-base/chart/templates/configmap.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/templates/persistantVolumeClaim.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
This pr will contain changes to the way labels are handles within the tenant-base chart,
The reason for this change is that currently we're using the default helpers functions to get labels, this does not suit the way we have build the chart, this pr tries to fix this.
Changelog:
- Add new label helpers
- Remove old label helpers
- Removed unused helpers
- Removed 'chart.name' and 'chart.fullname' - We're not going to use the overrides so keeping the helpers seems redudant
Checklist:
> Change labels to better fix best practice in our usecase

- charts/tenant-base/README.md
- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/_helpers.tpl
- charts/tenant-base/chart/templates/configmap.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/templates/persistantVolumeClaim.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
Reverts distributed-technologies/helm-charts#403
The changes break a lot of functionality. 
1. New naming of KafkaTopic resources -> Breaks Kyverno generate policy that generates Kafka topics[1]
2. Removed label "app.kubernetes.io/app" from deployment pods -> breaks CiliumNetworkPolicy access to KafkaTopics[2]
These are critical features that we found and therefore we choose to revert the whole PR.
[1]https://dev.azure.com/energinet/Team%20DT/_git/flux-fleet-repo?path=/infrastructure/kyverno/kyverno-policies/base/generate_kafka_topic.yaml&version=GBfeature/prometheus-tenant-access&line=33&lineEnd=34&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents
[2]https://dev.azure.com/energinet/Team%20DT/_git/flux-fleet-repo?path=/infrastructure/kyverno/kyverno-policies/base/generate_ciliu …
> Revert "Change labels to better fix best practice in our usecase"

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/configmap-kafka-topic.yaml
When the configmap is digested by Kyverno the cm name is set as a lable value on the generated resource. This value cannot be more than 63 chars.
Checklist:
> tenant-base: Ensure the cm name is not longer than 64 chars

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
I have added the possibility for our tenants to mount a configmap as environment variables in a pod. This is done to make it easier for tenants to use environment variables in their pods and easier for them to understand how to mount them.
Checklist:
> tenant-base: Implemented possibility to mount configmaps as environment variables

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/templates/servicemonitor.yaml
This should make labels display the same as metadata.name does.
fixing bug/331814
Checklist:
* [ x] I have bumped the chart version
* [ x] I have documented my changes if this is needed
* [ x] I have described my changes in the "description of your changes" field
* [ x] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ x] I have created the necessary tests in the chart, if they are possible/necessary
* [ x] I have squashed commits if necessary
> Add 'fullName' variables to all templates that uses the 'release.Name-Name' repeatedly

- .github/workflows/lint-and-test.yaml
actions-setup-minikube broke somehow and it is likely fixed in
v2.7.2[1], but using the minikube version in the runner image should be
less fragile.
[1] https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.2
---
Checklist:
> ci: Fix broken minikube by using version shipped in the runner image

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
We do not want our users to deal with labels in the network policies as this subject is already complicated enough as is. They now have to deal with release name and deployment name instead.
Checklist:
> Remove labels from network policies

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
More than one / is not allowed in the label name of a Kubernetes resource
Checklist:
> Conforming to the k8s resource label naming conventions

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/values.yaml
The users need to be able to set their own probes
Checklist:
> Enable configurable probes
