distributed-technologies/helm-charts

- .github/configs/ct-install.yaml
- .github/configs/ct-lint.yaml
- .github/workflows/docker-build-push.yaml
- charts/argo-cd/chart/.helmignore
- charts/argo-cd/chart/Chart.yaml
- charts/argo-cd/chart/values.yaml
- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/values.yaml
I have added argocd as a chart and added it to the relevant configs as well as pointed nidhogg to it
Checklist:
> Added argo-cd as helm chart

- .github/configs/ct-install.yaml
- .github/configs/ct-lint.yaml
- .github/workflows/publish.yaml
- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
I have changed the argo-cd nidhogg dependency to our proxy chart and updated the Chart.lock file. 
Checklist:
> Changed nidhogg dependency, updated .lock file

- README.md
Added an entry to the README on how to add a helm chart to the mono repo
Checklist:
> Added an entry to the README on how to add a helm chart to the mono repo

- charts/artifact-registry/chart/Chart.yaml
> Fix chart name.

- charts/loadbalancer/chart/Chart.yaml
- charts/loadbalancer/chart/values.yaml
Added version tags in stead of main
Checklist:
> Set image tags and remove main tag

- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/templates/nidhogg.yaml
- charts/nidhogg/chart/values.yaml
> added functionality to disable self reference.

- charts/kafka/chart/Chart.yaml
- charts/kafka/chart/scripts/test_consumer_producer.sh
- charts/kafka/chart/templates/kafka-operator.yaml
- charts/kafka/chart/values.yaml
Extracting the listeners for the Kafka cluster to the values file. There must be 1 entry in the listeners list, which is why we cannot leave it empty.
Checklist:
> extracting listeners to values file

- charts/nidhogg/chart/Chart.yaml
- charts/nidhogg/chart/templates/nidhogg.yaml
Added dummy value to nidhogg template
Checklist:
> Added dummy value to nidhogg template

- .github/workflows/dependency-checker.yaml
Removed reviewers and made it so workflow is run on the 1st of the month
Checklist:
> Removed reviewers and made it so workflow is run on the 1st of the month

- charts/lightvessel/chart/Chart.yaml
- charts/lightvessel/chart/templates/_ingress.yaml
I have created an if statement that checks if ingress is enabled in the values file
Checklist:
> Made ingress optional with if condition

- .github/configs/ct-lint.yaml
- charts/cortex/README.md
- charts/cortex/chart/.helmignore
- charts/cortex/chart/Chart.yaml
- charts/cortex/chart/templates/bkt-claim.yaml
- charts/cortex/chart/values.yaml
I have added the cortex umbrella chart and a ceph-bucket-claim.
The configuration is has been moved to yggdrasil which will come in another pr.
Checklist:
> Cortex: Added Cortex umbrella chart, with ceph-bucket-claim

- .github/configs/ct-install.yaml
- .github/configs/ct-lint.yaml
- charts/grafana-agent-operator/chart/.helmignore
- charts/grafana-agent-operator/chart/Chart.yaml
- charts/grafana-agent-operator/chart/values.yaml
- charts/grafana-agent/chart/.helmignore
- charts/grafana-agent/chart/Chart.yaml
- charts/grafana-agent/chart/templates/cAdvisor-service-monitor.yaml
- charts/grafana-agent/chart/templates/cluster-role-binding.yaml
- charts/grafana-agent/chart/templates/cluster-role.yaml
- charts/grafana-agent/chart/templates/grafana-agent.yaml
- charts/grafana-agent/chart/templates/kubelet-service-monitor.yaml
- charts/grafana-agent/chart/templates/logs-instance.yaml
- charts/grafana-agent/chart/templates/metrics-instance.yaml
- charts/grafana-agent/chart/templates/pod-logs.yaml
- charts/grafana-agent/chart/templates/serviceaccount.yaml
- charts/grafana-agent/chart/values.yaml
I have added the grafana agent operator proxy chart
I have created the grafana agent chart with the necessary resources
I have added both new charts to ct-lint and ct-install
Checklist:
> Grafana-agent: Added agent and agent-operator

- charts/cortex/chart/Chart.yaml
I changed the name in the Chart.yaml to not be capitaliced.
Checklist:
> Cortex: Name was writen with capital

- charts/nidhogg/chart/Chart.lock
- charts/nidhogg/chart/Chart.yaml
nidhogg: bumped argo dependency version
Checklist:
> nidhogg: bumped argo dependency version

- .gitignore
- charts/kafka-topic-replicator/container/Dockerfile
- charts/kafka-topic-replicator/container/README.md
- charts/kafka-topic-replicator/container/app/kafka_topic_replicator.py
- charts/kafka-topic-replicator/container/poetry.lock
- charts/kafka-topic-replicator/container/pyproject.toml
- charts/kafka-topic-replicator/container/tests/test_kafka_topic_replicator.py
This PR addresses the application part of a Kafka topics replicator. We build and test using Docker and Poetry Infrastructure will come later. 
Checklist:
> Initial Kafka Topic replicator

- charts/resource-helper/README.md
- charts/resource-helper/chart/.helmignore
- charts/resource-helper/chart/Chart.yaml
- charts/resource-helper/chart/templates/_helper.tpl
- charts/resource-helper/chart/templates/networkPolicy.yaml
- charts/resource-helper/chart/templates/project.yaml
- charts/resource-helper/chart/templates/resourceQuota.yaml
- charts/resource-helper/chart/values.yaml
The resource-helper chart is a helper chart that will
facilitate the creation of ArgoCD project, Resource Quotas
and network policies
Checklist:
> Resource helper chart

- charts/lightvessel/chart/Chart.yaml
- charts/lightvessel/chart/templates/_networkPolicy.yaml
Network policy resource name my not be empty
Checklist:
> Lightvessel: add config name to network-policy

- charts/external-dns/chart/Chart.yaml
- charts/external-dns/chart/values.yaml
Resource limits are required to deploy in a namespace with Resource Quotas enabled.
Checklist:
> external-dns: Add resource limits

- .github/configs/ct-install.yaml
- .github/configs/ct-lint.yaml
- charts/squid/README.md
- charts/squid/chart/.helmignore
- charts/squid/chart/Chart.yaml
- charts/squid/chart/templates/_helpers.tpl
- charts/squid/chart/templates/crt-secret.yaml
- charts/squid/chart/templates/deployment.yaml
- charts/squid/chart/templates/service.yaml
- charts/squid/chart/templates/squid-config-cm.yaml
- charts/squid/chart/values.yaml
- charts/squid/container/Dockerfile
**Description of your changes:** Add squid forward proxy for testing air-gapped functionality.
Checklist:
---
~Hmm, is access logging to stdout working?~
> Add squid service

- charts/vault/chart/Chart.yaml
- charts/vault/chart/templates/_helpers.tpl
- charts/vault/chart/templates/configmap.yaml
- charts/vault/chart/templates/deployment.yaml
- charts/vault/chart/templates/pvc.yaml
- charts/vault/chart/values.yaml
The chart has been redone from scratch with auto unsealing.
Checklist:
> vault: Redo the chart with auto unsealing

- charts/fwd-proxy/chart/Chart.yaml
- charts/fwd-proxy/chart/config/Caddyfile
- charts/fwd-proxy/chart/templates/configmap.yaml
- charts/fwd-proxy/chart/values.yaml
Misc fixes, see the commit messages for details.
Checklist:
> fwd-proxy: Misc fixes

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
> tenant-base: Add support for network policies

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/values.yaml
> tenant-base: Fix nil pointer reference when 'retention' for kafkaTopic is not defined

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/values.yaml
Added toggle to deployments so they can be disabled.
Checklist:
> Added toggle to deployments

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
Changed name of referenced configmap so it automatically prefixes
Checklist:
> Changed name of referenced configmap

- charts/tenant-base/README.md
- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/_helpers.tpl
- charts/tenant-base/chart/templates/configmap.yaml
- charts/tenant-base/chart/templates/deployment.yaml
- charts/tenant-base/chart/templates/externalsecret.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
- charts/tenant-base/chart/templates/networkpolicy.yaml
- charts/tenant-base/chart/templates/persistantVolumeClaim.yaml
- charts/tenant-base/chart/templates/service.yaml
- charts/tenant-base/chart/values.yaml
- charts/tenant-base/docs/deployment.md
Uno-reverse flippety-flip-flop label PR changes
> Revert "Revert "Change labels to better fix best practice in our usecase""

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/servicemonitor.yaml
To get prometheus to scrape metrics we add a ServiceMonitor for each service of a Deployment
Checklist:
> Add ServiceMonitor for each service

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/deployment.yaml
We need to ensure that the pods of a deployment is redeployed on configmap updates.
Checklist:
> Ensure pods are redeployed on configmap update

- charts/tenant-base/chart/Chart.yaml
- charts/tenant-base/chart/templates/kafkatopic.yaml
> kafkaTopic: prefixed with release namespace
